In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("C:/Users/kesha/Downloads/Advertising.csv")

In [7]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [23]:
'''  Train | Test Split Procedure
Clean and adjust data as necessary for X and y
Split Data in Train/Test for both X and y
Fit/Train Scaler on Training X Data
Scale X Test Data
Create Model
Fit/Train Model on X Train Data
Evaluate Model on X Test Data (by creating predictions and comparing to Y_test)
Adjust Parameters as Necessary and repeat steps 5 and 6
'''

'Train | Test Split Procedure\nClean and adjust data as necessary for X and y\nSplit Data in Train/Test for both X and y\nFit/Train Scaler on Training X Data\nScale X Test Data\nCreate Model\nFit/Train Model on X Train Data\nEvaluate Model on X Test Data (by creating predictions and comparing to Y_test)\nAdjust Parameters as Necessary and repeat steps 5 and 6\n'

In [8]:
X=df.drop('sales',axis=1)
y=df['sales']

#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
from sklearn.linear_model import Ridge

In [12]:
# Poor Alpha Choice on purpose!
model = Ridge(alpha=100)

In [13]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [14]:
y_pred = model.predict(X_test)

In [15]:
y_pred

array([15.34908128, 17.05755308, 12.73784965, 16.18231062, 10.85075815,
        9.87999576, 17.6105132 , 15.80786278, 11.32616781, 17.30158479,
       12.8883864 , 13.64670913, 13.71636726, 18.83377117, 17.38617584,
       11.59912699, 14.88899736, 10.07145317, 10.14692243, 17.90771073,
       10.25837266, 16.71492563, 20.57087744, 19.66643199, 10.14020781,
       13.40084066, 18.09910709, 10.80433113, 13.00876939, 13.79206361,
       12.73015096, 17.42108555, 11.50183684, 10.10362749, 16.18778637,
       10.45161746, 11.25953403, 10.42658319, 12.30681396, 11.82281519,
       14.75707677, 11.58372535, 12.01609545, 10.90016204, 12.55896716,
       11.62961585, 10.8495293 , 15.74187916, 14.09264772, 18.45114683,
       13.43419788, 14.05075373, 16.0980788 , 12.07046074, 13.15048011,
        8.75095421, 19.21013193, 12.92686996, 16.49277745, 14.83525505])

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:

mean_squared_error(y_test,y_pred)

7.341775789034128

In [18]:
model = Ridge(alpha=0.56)

In [19]:
model.fit(X_train,y_train)

Ridge(alpha=0.56)

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([15.73801575, 19.58315825, 11.46234626, 17.00143228,  9.18574206,
        7.03936645, 20.26230201, 17.28319474,  9.78924036, 19.20382657,
       12.40682936, 13.88719357, 13.72422206, 21.26641765, 18.41895497,
        9.99625142, 15.54551784,  7.71036551,  7.58014112, 20.37863332,
        7.81442364, 18.22749396, 24.64687547, 22.79344605,  7.99766391,
       12.66052877, 21.43350797,  8.08051602, 12.4278849 , 12.52273852,
       10.79962727, 19.2281913 , 10.08242685,  6.74275288, 17.30449917,
        7.79424134,  9.273121  ,  8.29725275, 10.59857948, 10.64571114,
       13.03531115,  9.78974746, 10.23322077,  8.07531131, 11.57551977,
       10.09724264,  9.0131756 , 16.25136684, 13.2511561 , 20.79357469,
       12.5071102 , 13.96710937, 17.54830596, 11.15181137, 12.56807871,
        5.53755514, 23.25169167, 12.62345749, 18.74887247, 15.18455502])

In [22]:
mean_squared_error(y_test,y_pred)

2.309830759753398

In [24]:
'''
Train | Validation | Test Split Procedure
This is often also called a "hold-out" set, since you should not adjust parameters based on the final test set, but instead use it only for reporting final expected performance.

Clean and adjust data as necessary for X and y
Split Data in Train/Validation/Test for both X and y
Fit/Train Scaler on Training X Data
Scale X Eval Data
Create Model
Fit/Train Model on X Train Data
Evaluate Model on X Evaluation Data (by creating predictions and comparing to Y_eval)
Adjust Parameters as Necessary and repeat steps 5 and 6
Get final metrics on Test set (not allowed to go back and adjust after this!)
'''

'\nTrain | Validation | Test Split Procedure\nThis is often also called a "hold-out" set, since you should not adjust parameters based on the final test set, but instead use it only for reporting final expected performance.\n\nClean and adjust data as necessary for X and y\nSplit Data in Train/Validation/Test for both X and y\nFit/Train Scaler on Training X Data\nScale X Eval Data\nCreate Model\nFit/Train Model on X Train Data\nEvaluate Model on X Evaluation Data (by creating predictions and comparing to Y_eval)\nAdjust Parameters as Necessary and repeat steps 5 and 6\nGet final metrics on Test set (not allowed to go back and adjust after this!)\n'

In [25]:
## CREATE X and y
X = df.drop('sales',axis=1)
y = df['sales']

In [26]:
######################################################################
#### SPLIT TWICE! Here we create TRAIN | VALIDATION | TEST  #########
####################################################################
from sklearn.model_selection import train_test_split

# 70% of data is training data, set aside other 30%
X_train, X_OTHER, y_train, y_OTHER = train_test_split(X, y, test_size=0.3, random_state=101)

# Remaining 30% is split into evaluation and test sets
# Each is 15% of the original data size
X_eval, X_test, y_eval, y_test = train_test_split(X_OTHER, y_OTHER, test_size=0.5, random_state=101)

In [27]:
len(X_train)

140

In [28]:
len(X_eval)

30

In [29]:
len(X_test)

30

In [30]:
# SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_eval = scaler.transform(X_eval)
X_test = scaler.transform(X_test)

In [31]:
from sklearn.linear_model import Ridge

In [32]:
# Poor Alpha Choice on purpose!
model = Ridge(alpha=100)

In [33]:
model.fit(X_train,y_train)

Ridge(alpha=100)

In [34]:
y_eval_pred = model.predict(X_eval)

In [35]:

from sklearn.metrics import mean_squared_error

In [36]:
mean_squared_error(y_eval,y_eval_pred)

7.320101458823871

In [37]:
model = Ridge(alpha=0.56)

In [38]:
model.fit(X_train,y_train)

Ridge(alpha=0.56)

In [39]:
y_eval_pred = model.predict(X_eval)

In [40]:
mean_squared_error(y_eval,y_eval_pred)

2.371565442171324

In [41]:
y_final_test_pred = model.predict(X_test)

In [42]:
mean_squared_error(y_test,y_final_test_pred)

2.2480960773354712

In [43]:
#Cross Validation with cross_val_score

In [44]:

## CREATE X and y
X = df.drop('sales',axis=1)
y = df['sales']

# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [45]:

model = Ridge(alpha=100)

In [46]:
from sklearn.model_selection import cross_val_score
# SCORING OPTIONS:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_val_score(model,X_train,y_train,
                         scoring='neg_mean_squared_error',cv=5)

In [47]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [48]:
abs(scores.mean())

np.float64(8.215396464543606)

In [49]:
model = Ridge(alpha=0.56)
# SCORING OPTIONS:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_val_score(model,X_train,y_train,
                         scoring='neg_mean_squared_error',cv=5)

In [50]:
abs(scores.mean())

np.float64(3.3439821853239087)

In [51]:
model.fit(X_train,y_train)
y_final_test_pred = model.predict(X_test)
mean_squared_error(y_test,y_final_test_pred)

2.309830759753398

In [52]:
'''
Cross Validation with cross_validate
The cross_validate function differs from cross_val_score in two ways:

It allows specifying multiple metrics for evaluation.

It returns a dict containing fit-times, score-times (and optionally training scores as well as fitted estimators) in addition to the test score.

For single metric evaluation, where the scoring parameter is a string, callable or None, the keys will be: - ['test_score', 'fit_time', 'score_time']

And for multiple metric evaluation, the return value is a dict with the following keys:

['test_<scorer1_name>', 'test_<scorer2_name>', 'test_<scorer...>', 'fit_time', 'score_time']
return_train_score is set to False by default to save computation time. To evaluate the scores on the training set as well you need to be set to True.
'''

"\nCross Validation with cross_validate\nThe cross_validate function differs from cross_val_score in two ways:\n\nIt allows specifying multiple metrics for evaluation.\n\nIt returns a dict containing fit-times, score-times (and optionally training scores as well as fitted estimators) in addition to the test score.\n\nFor single metric evaluation, where the scoring parameter is a string, callable or None, the keys will be: - ['test_score', 'fit_time', 'score_time']\n\nAnd for multiple metric evaluation, the return value is a dict with the following keys:\n\n['test_<scorer1_name>', 'test_<scorer2_name>', 'test_<scorer...>', 'fit_time', 'score_time']\nreturn_train_score is set to False by default to save computation time. To evaluate the scores on the training set as well you need to be set to True.\n"

In [53]:
X = df.drop('sales',axis=1)
y = df['sales']

# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# SCALE DATA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [55]:

from sklearn.model_selection import cross_validate
# SCORING OPTIONS:
# https://scikit-learn.org/stable/modules/model_evaluation.html
scores = cross_validate(model,X_train,y_train,
                         scoring=['neg_mean_absolute_error','neg_mean_squared_error','max_error'],cv=5)

In [56]:
scores

{'fit_time': array([0.00194073, 0.00099921, 0.00200152, 0.00199771, 0.00200343]),
 'score_time': array([0.00100112, 0.00100231, 0.00199986, 0.00099993, 0.00199676]),
 'test_neg_mean_absolute_error': array([-2.31243044, -1.74653361, -2.56211701, -2.01873159, -2.27951906]),
 'test_neg_mean_squared_error': array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
         -8.38562723]),
 'test_max_error': array([ -6.44988486,  -5.58926073, -10.33914027,  -6.61950405,
         -7.75578515])}

In [57]:
pd.DataFrame(scores)

fit_time  score_time  test_neg_mean_absolute_error  \
0  0.001941    0.001001                     -2.312430   
1  0.000999    0.001002                     -1.746534   
2  0.002002    0.002000                     -2.562117   
3  0.001998    0.001000                     -2.018732   
4  0.002003    0.001997                     -2.279519   

   test_neg_mean_squared_error  test_max_error  
0                    -9.325530       -6.449885  
1                    -4.944962       -5.589261  
2                   -11.396652      -10.339140  
3                    -7.024211       -6.619504  
4                    -8.385627       -7.755785

In [58]:
pd.DataFrame(scores).mean()

fit_time                        0.001789
score_time                      0.001400
test_neg_mean_absolute_error   -2.183866
test_neg_mean_squared_error    -8.215396
test_max_error                 -7.350715
dtype: float64

In [59]:
model = Ridge(alpha=1)

In [60]:
scores = cross_validate(model,X_train,y_train,
                         scoring=['neg_mean_absolute_error','neg_mean_squared_error','max_error'],cv=5)

In [61]:
pd.DataFrame(scores).mean()
# Need to fit the model first!
model.fit(X_train,y_train)
y_final_test_pred = model.predict(X_test)
mean_squared_error(y_test,y_final_test_pred)

2.3190215794287514